apiVersion: v1
kind: Service
metadata:
  name: check-service
spec:
  selector:
    app.kubernetes.io/name: check-depl
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080


